default_language_version:
    python: python3

repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: ""
    hooks:
      - id: pycln

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: ""
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: ""
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-builtin-literals

  - repo: https://github.com/PyCQA/flake8
    rev: ""
    hooks:
      - id: flake8
        additional_dependencies: [
          "git+https://gitlab.cee.redhat.com/cnv-qe/flake8-python-plugins.git",
          "pep8-naming"
        ]
