name: issue labeler
on:
  issue_comment:
    types: [created, edited]

jobs:
 label:
   runs-on: [ubuntu-latest]
   steps:
     - name: Label issues
       uses: andymckay/labeler@master
       if: startsWith(${{ github.event.comment.body }}, '/')
       with:
         add-labels: ${{ github.event.comment.body }}
