name: Add Reviewers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        reviewers: myakove,rnetser
        re-request-when-approved: true
        re-request-when-changes-requested: true
